baseURL = "/"
languageCode = "zh-cn"
title = "橘子的日志本"
theme = "yinyang"
publishDir = "docs" # Github Pages

[author]
name = "Soeur"
homepage = "https://gugugu.dev/"

[params]
headTitle = "Soeur"
mainSections = ["posts"]
favicon = "/favicon.ico"

[[params.socials]]
name = "About Me"
link = "/about"
[[params.socials]]
name = "Github"
link = "https://github.com/juzi5201314"
[[params.socials]]
name = "Email"
link = "mailto:juzi201314@gmail.com"